kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: boon.jian.lim@oracle.com
        send_resolved: false
        from: alert@limboonjian.com
        smarthost: smtp.email.us-phoenix-1.oci.oraclecloud.com:25
        require_tls: true